### ISSUE TITLE
Poloniex returnOrderTrades does not work

### ISSUE THREAD

**Issue by avolodin** [knowm/XChange#1844]
Can not receive order trades. The exceptions occurs
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of org.knowm.xchange.poloniex.PoloniexException out of START_ARRAY token

Please change return type for method returnOrderTrades in the class PoloniexAuthenticated:
from Map<String, PoloniexOpenOrder[]> returnOrderTrades(...)
to PoloniexUserTrade[] returnOrderTrades(...)

Thanks.

**Comment by npomfret** [comment]
This is often the case when the exchange returns an error message instead of the data.  The xchange java code possibly isn't checking for the error message.  If this is the case and you have the correct logging turned on you should be able to see the error message that's coming back from the exchange.

**Comment by timmolter** [comment]
The code in the Poloniex module will need to be fixed. A PR with the fix would be appreciated.

**Comment by earce** [comment]
This was updated
