### ISSUE TITLE
xchange-idex has no tests or examples

### ISSUE THREAD

**Issue by Rajat--Gupta** [knowm/XChange#2612]
Tried to write a simple test but encountered multiple bugs and design issues.
Please fix. @jnorthrup

**Comment by jnorthrup** [comment]
I have been working with The AuroraDev team and had to hold off on pursuing this to completion due to a bit of rapid backend redesign under the load.  there were some crucial test phase details that required a testnet instance which never materialized in the last mile of implementing trades and verifying order books.

my own personal usecases focus on the UserAccountInfo featureset and as mentioned, this is a backport of the version i use for those features.  

it is reasonable to get in touch with the auroradev team vie telegram and get the latest updates and see if they will disclose the API revisions 

I took this up on a bounty because I wrote it for the mentioned usecases anyways, and the orderbook was disabled and hasn't to my knowledge ever been turned back on. 

due to the easily juxtaposed currencies in trades, I disabled those soas to save someone the heartache of liquidating an asset when they intended a small test trade.  there may yet be a testnet they will provide access to however there were some priorities that took precedence over the Xchange module rewrite

**Comment by jnorthrup** [comment]
@trixprod apoligies for the NPE, btw, no that seems unlike the intended push.  it may be some time before I can address this.

other matters pulled me away from this and I wanted to push the in-testing progress and pick this up when the auroradev team had more cycles to address the API

**Comment by badgerwithagun** [comment]
Worth putting an explanatory exception in the code or somewhere really obvious to indicate that this implementation isn't working atm?  I can also confirm that this NPEs if you try and create an `IdexExchange`.

Tempted to just put in a PR which throws if you attempt to instantiate `IdexExchange`, unless there's anyone successfully using this for anything...

**Comment by jnorthrup** [comment]
There was a version submitted prior to the style guide priorities that
ensued.  I'm not able to give this much time right now but I am surprised
that instantiation isn't working.

**Comment by trixprod** [comment]
NPE and some design issues fixed by request #2693
