### ISSUE TITLE
Convert all toString() methods to Json

### ISSUE THREAD

**Issue by makarid** [knowm/XChange#2943]
Hello, i would like to ask you if it is OK to change all the toString() functions to convert the POJO to json format instead of just plain text. Thanks

**Comment by walec51** [comment]
toString should turn an object to a human friendly string is possible (like CurrencyPair::toString where it results to "BTC/USD") or a developer friendly string for debuging.

JSON is usually used for integration and you have libraries like Jackson with more control over that and they do not expect you classes to to serialization in toString methods.

Because of this I would be against it.

**Comment by makarid** [comment]
Thanks a lot for your response! So,i will find more options on the Jackson library in order to manipulate POJO to Json.
