### ISSUE TITLE
Kucoin 2.0 implemented? If so how to setup account?

### ISSUE THREAD

**Issue by andrewlin0410** [knowm/XChange#2963]
I wonder if the 2.0 API is implemented or I did something wrong.

I did this
 public static Exchange createKucoinExchange() {
        ExchangeSpecification exSpec = new KucoinExchange().getDefaultExchangeSpecification();
        exSpec.setSecretKey("...");
        exSpec.setApiKey("...");
//        exSpec.setExchangeSpecificParametersItem("Passphrase", "...");

        return ExchangeFactory.INSTANCE.createExchange(exSpec);
    }
    static Exchange kucoinExchange = createKucoinExchange();
    static AccountService kucoinAccountService = kucoinExchange.getAccountService();
    static TradeService kucoinTradeService = kucoinExchange.getTradeService();
but I got the following error:

java.lang.NoClassDefFoundError: com/kucoin/sdk/KucoinClientBuilder
	at org.knowm.xchange.kucoin.KucoinBaseService.<init>(KucoinBaseService.java:17)
	at org.knowm.xchange.kucoin.KucoinMarketDataServiceRaw.<init>(KucoinMarketDataServiceRaw.java:17)
	at org.knowm.xchange.kucoin.KucoinMarketDataService.<init>(KucoinMarketDataService.java:21)
	at org.knowm.xchange.kucoin.KucoinExchange.initServices(KucoinExchange.java:46)
	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:110)
	at org.knowm.xchange.kucoin.KucoinExchange.applySpecification(KucoinExchange.java:39)
	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:128)
	at Main.createKucoinExchange(Main.java:68)
	at Main.<clinit>(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.kucoin.sdk.KucoinClientBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 9 more
Help would be appreciated. Thanks

**Comment by andrewlin0410** [comment]
And is this necessary?
exSpec.setExchangeSpecificParametersItem("Passphrase", "...");

**Comment by badgerwithagun** [comment]
@andrewlin0410, yes, it's recently been implemented. I assume you are using the latest development snapshot?

Follow the example code in https://github.com/knowm/XChange/tree/develop/xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin - yes, you need the passphrase, but use the provided constant for the parameter name.

I think the class not found exception is probably because you need to resolve your maven dependencies. A new dependency was added to xchange-kucoin.

**Comment by andrewlin0410** [comment]
> @andrewlin0410, yes, it's recently been implemented. I assume you are using the latest development snapshot?
> Follow the example code in https://github.com/knowm/XChange/tree/develop/xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin - yes, you need the passphrase, but use the provided constant for the parameter name.
> I think the class not found exception is probably because you need to resolve your maven dependencies. A new dependency was added to xchange-kucoin.
Hi I looked at the example but I don't understand where this "System.getProperty()" is from. 
Do I need to do "System.setProperty()"? Why don't we just directly put the strings? 
And I am using the latest snapshot. I added the jar through modules in project structure in intellij. Is this the right way to add it? Do I still need to resolve maven dependency in this case? If so, how to resolve maven dependency. Sorry if these questions are stupid. I am not really good at coding.

**Comment by badgerwithagun** [comment]
> Hi I looked at the example but I don't understand where this "System.getProperty()" is from. Do I need to do "System.setProperty()"? Why don't we just directly put the strings?

This explains about system properties in Java: https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

Feel free to change the code to directly input the string instead.  The reason the code in GitHub doesn't do that is because developers who are working on this example and making changes to XChange need to be able to change it without risking actually saving their API key accidentally to GitHub.  By making it a system property, the developer can pass in their API key from the command line without actually modifying the code:
```
java -cp [snip] org.knowm.xchange.the.ClassName -Dapi-key=MYAPIKEY -Dapi-secret=MYSECRET
```
You probably don't care about this so can just replace it with the string.

**Comment by badgerwithagun** [comment]
>  I am using the latest snapshot. I added the jar through modules in project structure in intellij. Is this the right way to add it? Do I still need to resolve maven dependency in this case? If so, how to resolve maven dependency.

I'm afraid I don't use IntelliJ so can't help with that.

**Comment by timmolter** [comment]
https://github.com/knowm/XChange/wiki/Frequently-Asked-Questions#how-do-i-add-my-api-key-and-secret-key-to-an-exchangespecification
