### ISSUE TITLE
BitmexMarketDataService.getTrades fails for XBT/7D_U105 and XBT/7D_D95

### ISSUE THREAD

**Issue by badgerwithagun** [knowm/XChange#2969]
Seems to be consistently replicatable. Stack trace:
```
java.lang.NullPointerException: null
	at org.knowm.xchange.bitmex.BitmexAdapters.adaptOrderType(BitmexAdapters.java:212)
	at org.knowm.xchange.bitmex.BitmexAdapters.adaptTrade(BitmexAdapters.java:135)
	at org.knowm.xchange.bitmex.BitmexAdapters.adaptTrades(BitmexAdapters.java:85)
	at org.knowm.xchange.bitmex.service.BitmexMarketDataService.getTrades(BitmexMarketDataService.java:98)
```
The `BitmexPublicTrade.side` property is arriving as null.

I only spotted this while testing #2950. It doesn't affect me so I am unlikely to follow it up.

**Comment by jakubkalicki** [comment]
Not sure what is the reason for this and I don't have idea for the fix...

**Comment by trixprod** [comment]
I have created a pull request to prevent NPE. 
Tell me if i'm wrong but the Bitmex API itself doesn't return side no ?
BitmexPublicTrade [symbol=XBT7D_D95 price=0, size=39, time=Fri Mar 15 12:00:00 UTC 2019, side=null, tickDirection=null]

**Comment by timmolter** [comment]
You should print out the actual returned JSON, not the toString to really see what is returned.

**Comment by trixprod** [comment]
Is there a way to print all returned json from API calls ?
Some debug logs maybe ?

**Comment by timmolter** [comment]
Yes, it's in the Wiki.

**Comment by trixprod** [comment]
Json : 
`
{"timestamp":"2019-03-15T12:00:00.000Z","symbol":"XBT7D_U105","side":"","size":108,"price":0,"tickDirection":"ZeroPlusTick","trdMatchID":"d2d3efc0-00bc-2f9b-2dfa-1c83b2af06de","grossValue":1080000000,"homeNotional":10.8,"foreignNotional":0}
`

Size is empty string in Json and null in Object. Conversion to BitmexSide has no value for empty string.

The issue is also observable with tickDirection, sometimes Bitmex return an empty value.
But in that case, Xchange doesn't try to convert to a Xchange entity.

So, prevent NPE is the best solution imo.
