### ISSUE TITLE
How to include all jar in my project ?

### ISSUE THREAD

**Issue by straumat** [knowm/XChange#3325]
I'm making a multi exchange bot and I would like my bot to be able to connect easily to all the exchanges you support. To do so, i did not find another solution than including all the jars you produce in my POM. It's quite long and upadtes will be complicated. 
Do u have a better solution ? Thanks

**Comment by walec51** [comment]
you have to test every exchange one by one for you use case

don't assume that all modules here a equal and have all API features implemented

some don't even have trading implemented because no one had the time, some exchanges don't expose basic features in their API like batch order canceling - because of this don't

so as you see from the above - adding all modules with a single dependency given little to non convenience here
