### ISSUE TITLE
Kucoin upgraded the API key to version 2.0

### ISSUE THREAD

**Issue by straumat** [knowm/XChange#3982]
Hi everyone, I'm the creator of [Cassandre](https://github.com/cassandre-tech/cassandre-trading-bot) that uses XChange. Thanks for your wonderful work.

My testing bot uses Kucoin Sandbox and for 3 weeks, impossible to connect (401 error) with the credentials I'm using for 1 year. It still works on the Kucoin production server.

From what I read on their websites, they are changing their authentication : 
[To reinforce the security of the API, KuCoin upgraded the API key to version 2.0, the validation logic has also been changed. It is recommended to create and update your API key to version 2.0. The API key of version 1.0 will be still valid until May 1, 2021. Check new signing method](https://docs.kucoin.com/#general)

Do you know if Xchange supports those change ? At least, from what I understand, it can now be tested on their sandbox.

**Comment by earce** [comment]
@straumat I am not aware of anyone having done the necessary code changes to change the signing method to v2, but feel free to submit a PR making these changes!

**Comment by straumat** [comment]
@earce yes, I'm scared the upgrade in may broke XChange, I opened an issue at kucoin to ask them more about it. Is it just a configuration change or a code change. I will keep this issue updated with their reply.

**Comment by earce** [comment]
@straumat it really shouldn't be that concerning, if you change our way of creating the signature to accommodate their new v2 and it works in sandbox I would say that would a good sign.

**Comment by goberson** [comment]
@straumat @earce 
Hey guys,
Did you try something here? Since i'm working with KuCoin I have heavy interest on this point. More or less two weeks left... Unfortunately I did not study XChange (i'm only using it..) yet and it most probably would take me too much time to understand the architecture and where to change what to adapt to the new KuCoin API. In the meantime, here a bit of information:
https://support.kucoin.plus/hc/en-us/articles/900006465403-KuCoin-API-key-upgrade-operation-guide

Apparently there's a new header (KC-API-KEY-VERSION), and a new requirement, namely to encrypt the passphrase via the API-Secret.

I could probably help, if someone guides me to the right place where these "things" are done in the code... ;-)

**Comment by straumat** [comment]
@goberson Hi in fact, on the sanbox, i created a new API key (what they call 2.0 API key) and the sandbox login is working now. So maybe no change is required to Kucoin. I wait for their definitive reply before closing this issue

**Comment by goberson** [comment]
@straumat Oh, this looks like a positive thing. So you did not had the balls to go with that on production yet. Any plans to give it a try? Knowing Kucoin, i would not be surprised if they are differences between sandbox and prod. ;-)

**Comment by straumat** [comment]
@goberson In fact, it's in production :)
I'm the developer of [Cassandre](https://github.com/cassandre-tech/cassandre-trading-bot), a spring boot starter allowing Java developer to develop their own bot. And I'm in production since more than 6 months with Kucoin

**Comment by goberson** [comment]
@straumat Got it. So did I understand correctly that you use the API V2 Key on production?
Or only API V1 on production and API V2 on sandbox ?

**Comment by straumat** [comment]
API V2 Key on sandbox & production

**Comment by goberson** [comment]
Okay. Thank you. Then I'll give it a try too. ;-) And so we could close this issue right?
