### ISSUE TITLE
bitstamp v2 API should be taking UUID nonces

### ISSUE THREAD

**Issue by matt-nydig** [knowm/XChange#3991]
It appears that methods that call the Bitstamp v2 api are sending `Long` nonces rather than UUID nonces. This breaks with a nonce error much of the time.

Some background: I just upgraded some code that fetches balances from Bitstamp to xchange 5.0.6, which includes a change to use the v2 API for fetching balances: https://github.com/knowm/XChange/commit/dd134e31dd50663b30bb61ae19150e7b6d387e0f

Shortly after the change, we started getting 403's with an "Invalid nonce" message. I've taken a (newbie, not-too-detailed) look at your code, and it _looks_ like the nonce generation algorithm used for Bitstamp's v2 api still relies on sending a `Long` nonce, rather than a UUID.

Falling back to xchange 5.0.4 immediately fixed this error.

**Comment by earce** [comment]
Hi Matt,

Taking a glance at the Bitstamp API and I see that the V2 API does in fact have some significant changes from the V1 as far as expected nonce. We will probably need to create a custom Bitstamp nonce generator because the documentation has some pretty specific requirements namely:

- lowercase,
- 36 char string,
- each nonce can be used only once within a timeframe of 150 seconds.

I would think using Java's UUID.randomUUID().toString() would satisfy what this API wants. It returns 36 length string. If not writing a custom random string generator isn't too difficult. You do have the extremely unlikely event of a collision but a strong guarantee could be to create a map using something like guava or caffeine to evict nonces after they exceed 150 seconds in age. I think in most cases Java's UUID is probably good enough.

I don't know who else is using this right now but if you'd like you can definitely submit a PR for this and I can review it or offer further guidance.

**Comment by matt-nydig** [comment]
`UUID.randomUUID()` uses, according to Java's docs, a "a cryptographically strong pseudo random number generator." This implies 128 bits of high entropy data. There is no remotely realistic possibility, under these assumptions, and given the rate limits of the Bitstamp API, of generating a collision within 150 seconds. We should have a look at that... I'm a bit time constrained myself right now, though.

**Comment by earce** [comment]
Makes sense, sounds good to me!

**Comment by joakjo** [comment]
Bitstamp will also stop supporting HTTP API v1 later this year, which will require using the new v2 authentication (header based as opposed to sending key, signature and nonce as request parameters which both `BitstampAuthenticated` and `BitstampAuthenticatedV2` do atm)

[DEPRECATION WARNING
API v1 authentication and v1 endpoints are being deprecated and will soon no longer be available.](https://www.bitstamp.net/api-deprecated/)

**Comment by mathvdh** [comment]
Hi All,

Any progress on this ? I was trying to check it a bit but I'm still lost ... I'm willing to spend some time on it but I only made a few (very small) contributions to this project and this one seems more substantial ... Any hints ?

**Comment by earce** [comment]
@joakjo that's interesting because some of the API endpoint present in v1 I do not see in v2

**Comment by mathvdh** [comment]
I've implemented locally all the described changes but I'm still getting a `Invalid nonce (HTTP status code: 403)`. Even if when I debug I see that the nonce in the body is correct , example body :

```
key=[Redacted]&signature=45A9420FB393AD3183D06A66DF891F987D829B00EAEE3F95FAACD22FD79EC0A2&nonce=078fc0b4-2685-4a0f-9102-419f93709108&amount=0.001&price=30000.0
```

Which has a correct nonce it seems : 078fc0b4-2685-4a0f-9102-419f93709108

To be clean All the xchange lib tests are passing, but I have my own test suite which actually tests with real (test) accounts behind and this is failing ...

**Comment by joakjo** [comment]
@mathvdh Hi

to use the 36 char string as nonce instead of a number you need to use auth version 2.

version 1 will not accept a string as nonce and you will get `Invalid nonce` as you described.

In version 2 you need to put key, signature and nonce as headers instead of as parameters, along with some other headers (like version).

Compare the two versions here: https://www.bitstamp.net/api-deprecated/ under
V1 AUTHENTICATION METHOD
V2 AUTHENTICATION METHOD

**Comment by mathvdh** [comment]
Hi @joakjo , Yes I was seeing that we are actually sending form params instead of headers .. I'm working on it .. Thanks
