### ISSUE TITLE
OKEx V5 API support

### ISSUE THREAD

**Issue by tonykwok1992** [knowm/XChange#3994]
https://www.okex.com/docs-v5/en/#overview

**Comment by earce** [comment]
These things tend to be self-serve, feel free to pull a PR!

**Comment by davidjirovec** [comment]
As of March 31, API v5 is available to all Unified Account users. Since API v3 will be discontinued shortly after v5 has been fully rolled out, we encourage users to upgrade their API to v5 for better functionalities and a more seamless trading experience.

https://www.okex.com/academy/en/api-trading-explained-okex-api-v5-upgrade-capabilities-benefits

For anybody who already uses xchange okex integration with v3 api, be prepared for discontinue.

**Comment by zpaimon** [comment]
Any plan for this issue ?
