### ISSUE TITLE
Kucoin: Market order buying base currency with quote currency not working

### ISSUE THREAD

**Issue by javialbors** [knowm/XChange#4035]
I tried placing market orders for some coins but when setting the amount in the market order constructor it gets referred to the base currency amount not the quote currency amount. For example: I tried buying DOGE coin with 5 USDT so I executed this:

```
private static void marketBuy() throws IOException {
        TradeService tradeService = kucoin.getTradeService();
        MarketOrder order = new MarketOrder(Order.OrderType.BID, BigDecimal.valueOf(5), new CurrencyPair(Currency.getInstance(ticker), Currency.getInstance(pair)));
        tradeService.placeMarketOrder(order);
    }
```

I expected to buy as many DOGE coins as I could with 5 USDT but instead I bought 5 DOGEs:

<img width="1268" alt="Captura de pantalla 2021-04-26 a las 21 00 52" src="https://user-images.githubusercontent.com/60600307/116136371-82a31180-a6d2-11eb-92e4-39050c91c93b.png">

In the [Kucoin API documentation](https://docs.kucoin.com/#place-a-new-order) it's written that there are two optional parameters to place a market order; size (desired amount in base currency) and funds (desired amount in quote currency). 
However, market order constructors chose base currency over fund currency...

**Comment by earce** [comment]
@straumat maybe you can opine?

**Comment by straumat** [comment]
@javialbors & @earce
Hi, I add a similar [issue](https://github.com/knowm/XChange/issues/4028) with Coinbase library and I wrote a fix that seems to work. But my project [Cassandre](https://github.com/cassandre-tech/cassandre-trading-bot) is using Kucoin Xchange library since more than 6 months and I have no problem. Positions, opening & closing market orders works very well.

Can you compare your problem to the coinbase issue I posted ?

**Comment by straumat** [comment]
@earce I think this issue should be closed
