### ISSUE TITLE
[FTX] No implementation of cancelOrder for a sub-account

### ISSUE THREAD

**Issue by mathvdh** [knowm/XChange#4095]
There is no possibility to cancel an order if you are using a sub-account in the current implementation.

The only cancelOrder function is : 

```
@Override  
public boolean cancelOrder(String orderId) throws IOException { 
   return cancelFtxOrder(orderId);  
}
```

There is no `cancelOrderForSubaccount` version like there is for example : 

`placeLimitOrder(LimitOrder limitOrder)`

and

`placeLimitOrderForSubaccount(String subaccount, LimitOrder limitOrder)`

I'm not sure if it's _THE_ way to go to have a version of every function with a postfix of `ForSubaccount` but it does work so I propose to add a cancelOrderForSubaccount version.

If nobody disagrees I will submit a PR.

**Comment by mathvdh** [comment]
I have been checking it a bit more.

Some things bother me 

1) Can't we just have a version of `placeLimitOrder` which has one additional argument instead of `placeLimitOrderForSubaccount` ?

Like this : 

```
placeLimitOrder(LimitOrder limitOrder) {..}
placeLimitOrder(LimitOrder limitOrder, String subaccount) {..}
```

(This does apply to many more functions ...) ?
Would it mess with the fact that placeLimitOrder is an `@Override ` ?


2) Why is the orders of the parameters different ? Why is the subaccount the first argument ? This is not clean to me .. ?

The thing is that if you go look at the implementation lower (in FtxTradeServiceRaw) it's calling for example : 

```
try {
      return ftx.cancelOrder(
              exchange.getExchangeSpecification().getApiKey(),
              exchange.getNonceFactory().createValue(),
              signatureCreator,
              null,
              orderId)
              .isSuccess();
    } catch (FtxException e) {
      throw new FtxException(e.getMessage());
    }
```

So what I mean is that the lower levels expect a subaccount or null ...

Anyway 1) and 2) are independant but I would like to have some opinions on this.

@earce  ?

Thanks

**Comment by mathvdh** [comment]
I'm not against 2) specifically, if there is a reason for it like it's implemented like this on other exchanges I would like to know or understand it .. that's it.

**Comment by makarid** [comment]
@mathvdh not all exchanges have subaccounts, so if you want to implement something specifically for one exchange in this example Ftx, you will need to create a new function on the Ftx.....Raw class.

**Comment by mathvdh** [comment]
@makarid well at the moment : `placeLimitOrderForSubaccount` is implemented on the `TradeService` class and not the `TradeServiceRaw` class ... so that's why I'm asking my questions ...

**Comment by mathvdh** [comment]
And other methods like `xxxForSubaccount` too ...

**Comment by makarid** [comment]
@mathvdh i am sorry, i didn't see that. In my opinion it is best to have them on Raw class. I don't remember if i put them there or someone else.

**Comment by makarid** [comment]
@mathvdh you can implement the cancelOrder(CalcelOrderParams) function in order to cancelOrders on subaccounts

**Comment by walec51** [comment]
yes, placeLimitOrderForSubaccount should be moved to the *Raw class

**Comment by imTigger** [comment]
The `getFtxOrderHistoryForSubaccount` and many more methods are missing too.

When I hacking the code, I come up with an idea:
Instead of implementing every `*ForSubaccount` method,
will it be a good idea to just use `exchange.getExchangeSpecification().getUserName()` as subaccount parameter?

Then we just need to pass `exSpec.setUserName("some-subaccount")` to `ExchangeSpecification` when creating the exchange,
and subsequence calls to all services will use that as subaccount.
If it's not specified it naturally null, which works as before.

I am new to this project, don't know if this will break any other things.

**Comment by imTigger** [comment]
The `getFtxOrderHistoryForSubaccount` and many more methods are missing too.

When I hacking the code, I come up with an idea:
Instead of implementing every `*ForSubaccount` method,
will it be a good idea to just use `exchange.getExchangeSpecification().getUserName()` as subaccount parameter?

Then we just need to pass `exSpec.setUserName("some-subaccount")` to `ExchangeSpecification` when creating the exchange,
and subsequence calls to all services will use that as subaccount.
If it's not specified it naturally null, which works as before.

I am new to this project, don't know if this will break any other things.

**Comment by mathvdh** [comment]
@imTigger this does sound like a good idea actually ... It would be more transparent like this ..
What do other people think ?

**Comment by makarid** [comment]
I also like the idea of @imTigger

**Comment by imTigger** [comment]
Well, it would be more straightforward to deal with subaccounts.

One problem is that, current release (5.0.8) have implemented `*ForSubaccount` methods,
and they are on `TradeService` not `TradeServiceRaw`.

If now we remove `*ForSubaccount` methods,
existing project using this library will break (i.e. backward-incompatible).

Do we need to consider this or maybe release it next major release?

**Comment by mathvdh** [comment]
We can close this issue as it's resolved in the PR above
